# Generated by Django 5.0.6 on 2024-07-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoMenu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomCakeRquest',
            new_name='CustomCakeRequest',
        ),
    ]
