# Generated by Django 5.0.7 on 2024-08-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoMenu', '0003_cateringrequest_email_customcakerequest_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoMenu.customer')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoMenu.purchase')),
            ],
        ),
    ]
