# Generated by Django 5.0.7 on 2024-08-05 21:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoMenu', '0004_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
