# Generated by Django 5.0.7 on 2024-08-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoMenu', '0005_purchase_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='order_id',
            field=models.PositiveIntegerField(),
        ),
    ]
