# Generated by Django 5.0.7 on 2024-08-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoMenu', '0006_alter_purchase_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
