# Generated by Django 5.0.7 on 2024-08-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoMenu', '0009_product_featured_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeryclass',
            name='class_level',
            field=models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=20),
        ),
    ]
