# Generated by Django 5.0.7 on 2024-08-20 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoMenu', '0010_alter_bakeryclass_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryclass',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bakeryclass',
            name='time',
            field=models.TimeField(default=datetime.time(14, 45, 1, 863977)),
        ),
    ]
